attributes:
  join_id: 'regionId'
  attribute_name: 'name'
  attribute_population: 'pop2015'
  attribute_id: 'natcode'
  attribute_id_poliline: 'id'
  attribute_neighbours: 'neighbours'
  attribute_lines: 'lines'

parameters:
  nr_of_districts : 120
  cooling_schedule: 0.99
  initial_temperature: 5
  final_temperature: 0.001
  iterations: 0
  small_partition: 5
  upper_limit: 5
  neighbourhood: [-1,1,3,1,3]
  weight_vectors : [[0.5,0.5]]
  minnr_of_unit : 2
  max_iter: 25
  max_size_pareto: 100
